---

# Checks whether the KUBECONFIG file, defined in 'kktl_kubeconfig', exists

- name: Stat kubectl file
  ansible.builtin.stat:
    path: "{{ ktl_kubeconfig }}"
  register: ktl_file

- name: Assert config file exists
  ansible.builtin.assert:
    that: ktl_file.stat.exists
    fail_msg: "KUBECONFIG file '{{ ktl_kubeconfig }}' does not exist"
