---

# (Optionally) Install kubectl

- name: Install kubectl
  include_role:
    name: githubixx.kubectl
  vars:
    kubectl_owner: "{{ ansible_effective_user_id }}"
    kubectl_group: "{{ ansible_effective_group_id }}"
    kubectl_os: "{{ ansible_os_family | lower }}"
    kubectl_checksum_binary: ""
    kubectl_version: "{{ ktl_kubectl_version }}"
  when:
  - not ansible_check_mode
  - ktl_install_kubectl | bool
  
# Makes sure the 'kubectl' command exists

- name: Find kubectl
  command: which kubectl
  changed_when: no
  register: kubectl_check

- name: Assert kubectl is installed
  fail:
    msg: "kubectl cannot be found"
  when: kubectl_check.rc != 0

- name: Get existing kubectl process
  shell: ps -ef | grep kubectl | grep -v grep | awk '{print $2}'
  changed_when: no
  register: kubectl_process

- name: Assert no existing kubectl process
  assert:
    that: kubectl_process.stdout | length == 0
    fail_msg: "An existing kubectl is running. Do you need to 'kill {{ kubectl_process.stdout }}'?"
