---

# Checks whether the KUBECONFIG file, defined in 'kc_kubeconfig', exists

- name: Stat kubectl file
  stat:
    path: "{{ kc_kubeconfig }}"
  register: kc_file

- name: Assert config file exists
  assert:
    that: kc_file.stat.exists
    fail_msg: "KUBECONFIG file '{{ kc_kubeconfig }}' does not exist"
