---

# (Optionally) Install kubectl

- name: Install kubectl
  ansible.builtin.include_role:
    name: githubixx.kubectl
  vars:
    kubectl_owner: "{{ ansible_effective_user_id }}"
    kubectl_group: "{{ ansible_effective_group_id }}"
    kubectl_os: "{{ ansible_os_family | lower }}"
    kubectl_checksum_binary: ""
    kubectl_version: "{{ ktl_kubectl_version }}"
  when:
  - not ansible_check_mode
  - ktl_install_kubectl | bool

# Makes sure the 'kubectl' command exists

- name: Find kubectl
  ansible.builtin.command: which kubectl
  changed_when: no
  register: k8s_kubectl_kubectl_check

- name: Assert kubectl is installed
  ansible.builtin.fail:
    msg: kubectl cannot be found
  when: k8s_kubectl_kubectl_check.rc != 0

- name: Get existing kubectl process
  ansible.builtin.shell: set -o pipefail && ps -ef | grep kubectl | grep -v grep | awk '{print $2}'
  args:
    executable: /bin/bash
  changed_when: no
  register: k8s_kubectl_kubectl_process

- name: Assert no existing kubectl process
  ansible.builtin.assert:
    that: k8s_kubectl_kubectl_process.stdout | length == 0
    fail_msg: "An existing kubectl is running. Do you need to 'kill {{ k8s_kubectl_kubectl_process.stdout }}'?"
