---

# Kills a process (expected to be a kubectl process)

- name: Check variables
  ansible.builtin.assert:
    that:
    - ktl_pid is defined

# Stop kubectl

- name: Display PID
  ansible.builtin.debug:
    msg: "PID={{ ktl_pid }}"

- name: Kill kubectl
  ansible.builtin.command: kill {{ item }}
  changed_when: no
  with_items: "{{ ktl_pid }}"

- name: Wait for kubectl to stop
  ansible.builtin.wait_for:
    path: /proc/{{ item }}/status
    state: absent
  with_items: "{{ kubectl_process.stdout_lines }}"
  ignore_errors: true
  register: k8s_kubectl_killed_processes

- name: Force kill stuck kubectl
  ansible.builtin.command: kill -9 {{ item }}
  register: k8s_kubectl_kill_output
  changed_when: k8s_kubectl_kill_output.rc != 0
  with_items: "{{ k8s_kubectl_killed_processes.results | select('failed') | map(attribute='item') | list }}"
