---

# Restore a database using kubectl to port-forward to a database Pod
# hosted on a cluster, optionally sourcing the file from an S3 bucket.
# Requires a suitable 'kubectl' utility.

- hosts: localhost
  roles:
  - k8s_database_restore
