---

# Dump a database using kubectl to port-forward to a database Pod
# hosted on a cluster, optionally copying to an S3 bucket.
# Requires a suitable 'kubectl' utility.

- hosts: localhost
  roles:
  - k8s_database_dump
