---

# Put a file on an S3 bucket.
#
# We check some control variables but the user is expected to have
# defined suitable environment variables to allow the AWS S3 module to work
# (see https://docs.ansible.com/ansible/latest/collections/amazon/aws/s3_object_module.html)

- name: Check variables
  ansible.builtin.assert:
    that:
    - s3_bucket | string | length > 0
    - s3_src | string | length > 0

- name: Check bucket path
  ansible.builtin.assert:
    that:
    - not s3_bucket_directory | regex_search('^/')
    - not s3_bucket_directory | regex_search('/$')
    fail_msg: "s3_bucket_directory must be a relative path without leading or trailing slashes"
  when: s3_bucket_directory | string | length > 0

- name: Act with S3
  when: not ansible_check_mode
  block:

  # We create the bucket, then the path and then put the file
  # in separate stages because the STFC Echo service (S3 compatible)
  # does not like automatically creating buckets and paths.
  # AWS lets's us do all this in one task, but we are forced to use 3.
  #
  # AWS and Echo are chosen by the user by setting the environment variables
  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_URL and AWS_DEFAULT_REGION.
  #
  # The AWS_DEFAULT_REGION is not set for the STFC/Echo service.

  - name: Create the bucket
    amazon.aws.s3_bucket:
      name: "{{ s3_bucket }}"

  - name: Create the bucket path
    amazon.aws.s3_object:
      bucket: "{{ s3_bucket }}"
      object: "{{ s3_bucket_directory }}"
      mode: create

  - name: Put the file
    amazon.aws.s3_object:
      bucket: "{{ s3_bucket }}"
      object: "{{ s3_bucket_directory }}/{{ s3_src | basename }}"
      src: "{{ s3_src }}"
      mode: put
