---

# Some required variables...

kdd_db_namespace: ""
kdd_db_database: ""
kdd_db_kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

# Some with defaults...

kdd_db_file_basename: "backup"
kdd_db_pod: "database-0"
kdd_db_pod_port: "5432"
# Compression.
# Empty (none) or one of ".pgc", ".bz2", ".gz" or ".xz"
# See the Ansible postgresql_db module.
kdd_db_file_compression: ""

# Dump's 'extra-args' parameter,
# See the Ansible postgresql_db module.
kdd_db_dump_extra_args: "--clean"
# The local port to forward to the database pod
kdd_db_local_port: "5432"
# The local directory where you want the dump to be written.
# The file uses the database name with a .sql.gz extension.
kdd_db_dump_directory: /tmp

# Maximum length of time to allow an asynchronous kubectl to run.
# kubectl is run asynchronously and then killed by playbooks and roles.
# The timeout is simply a protection mechanism.
# Set it to something much higher than you expect the process to take.
kdd_db_port_forward_time_minutes: 60

# Copy downloaded file to S3?
kdd_db_s3_bucket: ""
kdd_db_s3_bucket_directory: ""
