---

# Some required variables...

kdc_db_namespace: ""
kdc_db_database: ""
kdc_db_kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"

# Some with defaults...

kdc_db_pod: "database-0"
kdc_db_pod_port: "5432"

# User, if set the role creates it
# and provides ownership to the restored database.
kdc_db_user: ""
kdc_db_user_password: "{{ lookup('env', 'KDC_DB_USER_PASSWORD') }}"
# Role attributes, like "SUPERUSER"?
kdr_db_user_attr_flags: ""

# The local port to forward to the database pod
kdc_db_local_port: "5432"

# The DB admin user
kdc_db_admin_user: postgres

# Maximum length of time to allow an asynchronous kubectl to run.
# kubectl is run asynchronously and then killed by playbooks and roles.
# The timeout is simply a protection mechanism.
# Set it to something much higher than you expect the process to take.
kdc_db_port_forward_time_minutes: 60
