---

# Collect pg_restore version information
# It's output is typically "pg_restore (PostgreSQL) 13.9 (Debian 13.9-0+deb11u1)"
# so we have to parse it. Since PostgreSQL 10 all version numbers are 2 digits.
#
# Outputs: -
#
# - 'kdr_restore_version_ok' is set to 'yes'
#       if the version is suitable for the chosen database.
# - 'kdr_db_error_message' is set to an error message
#       if the version is not suitable.

- name: Find pg_restore
  ansible.builtin.command: which pg_restore
  changed_when: no
  ignore_errors: yes
  register: pg_restore_check

- name: Assert pg_restore is installed
  ansible.builtin.fail:
    msg: pg_restore cannot be found. You must install a compatible pg_restore
  when: pg_restore_check.rc != 0

- name: Collect pg_restore info
  ansible.builtin.command: pg_restore --version
  changed_when: false
  register: pg_restore_info

- name: Set pg_restore version
  ansible.builtin.set_fact:
    pg_restore_version: "{{ pg_restore_info.stdout \
      | regex_replace('pg_restore \\(PostgreSQL\\) ([0-9]+\\.[0-9]+).*', '\\1') }}"

- name: Display pg_restore version
  ansible.builtin.debug:
    var: pg_restore_version

  # Ensure pg_restore is at least the same version as the database server

- name: Check
  when: not ansible_check_mode
  block:

  - name: Collect database info
    community.postgresql.postgresql_info:
      login_host: "127.0.0.1"
      login_user: "{{ kdr_db_admin_user }}"
      login_password: "{{ kdr_db_admin_password }}"
    register: postgresql_info

  - name: Display database version
    ansible.builtin.debug:
      var: postgresql_info.version.full

  - name: Check failure
    when: pg_restore_version is ansible.builtin.version(postgresql_info.version.full, '>=')
    block:

    - name: Set success
      ansible.builtin.set_fact:
        kdr_restore_version_ok: yes

  - name: Check failure
    when: pg_restore_version is ansible.builtin.version(postgresql_info.version.full, '<')
    block:

    - name: Set failure
      ansible.builtin.set_fact:
        kdr_restore_version_ok: no

    - name: Set error message
      ansible.builtin.set_fact:
        kdd_db_error_message: >-
          pg_restore ({{ pg_restore_version }}) is not compatible
          with ({{ postgresql_info.version.full }})

    - name: Display failure
      ansible.builtin.debug:
        var: kdr_db_error_message
