---

# Get a file from an S3 bucket.
#
# We check some control variables but the user is expected to have
# defined suitable environment variables to allow the AWS S3 module to work
# (see https://docs.ansible.com/ansible/latest/collections/amazon/aws/s3_object_module.html)

- name: Check variables
  assert:
    that:
    - s3_bucket | string | length > 0
    - s3_dest | string | length > 0

- name: Check bucket path
  assert:
    that:
    - not s3_bucket_directory | regex_search('^/')
    - not s3_bucket_directory | regex_search('/$')
    fail_msg: "s3_bucket_directory must be a relative path without leading or trailing slashes"
  when: s3_bucket_directory | string | length > 0

- name: Get the file from S3
  amazon.aws.s3_object:
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_bucket_directory }}/{{ s3_dest | basename }}"
    dest: "{{ s3_dest }}"
    mode: get
  when: not ansible_check_mode
