---
name: lint

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
- push

jobs:
  lint:

    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ./README.md
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Load cached virtualenv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
    - name: Pre-commit check
      run: |
        source .venv/bin/activate
        pre-commit run --all-files
    - name: Lint
      run: |
        source .venv/bin/activate
        yamllint .
        find . -type f -name '*.yaml.j2' -exec yamllint {} +
        ansible-lint
    - name: Check site-k8s-database-dump
      run: |
        source .venv/bin/activate
        ansible-playbook site-k8s-database-dump.yaml -e kdd_db_namespace=default -e kdd_db_database=database --check
    - name: Check site-k8s-database-restore
      run: |
        source .venv/bin/activate
        ansible-playbook site-k8s-database-restore.yaml -e kdr_db_namespace=default -e kdr_db_database=database --check
